### PR TITLE
Qt6 support

### PR DESCRIPTION
**Pull request by arBmind**
Continued #79

Upgraded to MetaData version 9.
* uses simpler string store, with absolute offsets.
* property types and argument types are automatically registered.
* properties store signals directly now.

Got it somewhat to work. The examples also work properly.
Everything compiles, nothing crashes anymore, but some tests still fail to run.

### CODE REVIEW

**Comment by ogoffart** [comment]
I quickly went over the code and it looks good.

Small detail i'm wondering about is the order of Qt6 and C++17 condition.
I think this would be better than the other way around

```c++
#if Qt  6
#else 
 #if c++17
 #else
#endif
```

I haven't tried if it works, but if you are confident enough, this should be merged, and a new version of verdigris should be released.

**Comment by arBmind** [comment]
Thank you @ogoffart for taking a look.

All tests are upgraded for Qt6 and work for me on Qt6 on Windows.
I have cleaned up the precompiler conditionals as well.

It seems we still need to upgrade the CI to cover Qt5.15.2 and Qt6.

**Comment by ogoffart** [comment]
Regarding the CI, I believe we should actually setup github actions since travis will disapear soon.

**Comment by arBmind** [comment]
I have added some Github actions, that Test Qt 5.15 with msvc2019, gcc and clang. Qt6 is tested with gcc and msvc2019.
For clang with libc++ and Qt6 we need a qt version built with the same configuration. So far I cannot find a public build with that.

**Pull request merged**
